#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Formatter de Ajuda com Rich Text
✅ Usa <pre> para exemplos de comandos
✅ Usa <code> para sintaxe
"""


def formatar_ajuda() -> str:
    """Formata manual do sistema com rich text"""
    return (
        "<b> MANUAL DO ORQUESTRADOR JURÍDICO</b>\n"
        "\n"
        "<b>🎯 COMANDOS PRINCIPAIS</b>\n"
        "━━━━━━━━━━━━━━━━━━━━\n"
        "\n"
        "<b>📋 Controladoria:</b>\n"
        "<pre>/prazos</pre>\n"
        "<i>Ver lista completa de prazos pendentes</i>\n"
        "\n"
        "<pre>/concluir &lt;ID&gt; [motivo]</pre>\n"
        "<i>Concluir um prazo</i>\n"
        "\n"
        "<b>Exemplos:</b>\n"
        "<code>/concluir 152</code>\n"
        "<code>/concluir 152 Petição protocolada</code>\n"
        "\n"
        "<pre>/concluidos</pre>\n"
        "<i>Ver auditoria de prazos concluídos</i>\n"
        "\n"
        "<pre>/corrigir &lt;ID&gt; &lt;nova_data&gt;</pre>\n"
        "<i>Corrigir data de um prazo</i>\n"
        "\n"
        "<b>Exemplo:</b>\n"
        "<code>/corrigir 152 2026-07-15</code>\n"
        "\n"
        "<b>🤖 Controle de Bots:</b>\n"
        "Use os botões inline no menu <b>🤖 Bots</b>\n"
        "• <code>executor</code> - Bot executor\n"
        "• <code>djen</code> - Bot DJEN\n"
        "• <code>ia</code> - Bot de IA/OCR\n"
        "\n"
        "<b>💡 DICAS DE USO</b>\n"
        "━━━━━━━━━━━━━━━━━━━━\n"
        "• Use os <b>botões inline</b> para navegar rapidamente\n"
        "• Clique em <b>✅ Concluir</b> diretamente no card do prazo\n"
        "• O sistema calcula automaticamente prazos <b>CPC/CPP/CLT</b>\n"
        "• Use <code>/corrigir</code> quando o prazo calculado estiver errado\n"
        "• Sempre informe o <b>motivo</b> ao concluir um prazo\n"
        "\n"
        "<b>🔍 SOBRE O COMANDO /CORRIGIR</b>\n"
        "━━━━━━━━━━━━━━━━━━━━\n"
        "<b>Use quando:</b>\n"
        "• O DJEN calculou o prazo errado\n"
        "• Houve suspensão do prazo\n"
        "• Necessário ajustar manualmente\n"
        "\n"
        "<b>Formato:</b> <code>/corrigir &lt;ID&gt; &lt;AAAA-MM-DD&gt;</code>\n"
        "<b>Exemplo:</b> <code>/corrigir 152 2026-07-20</code>\n"
        "\n"
        "<b>📞 SUPORTE</b>\n"
        "Em caso de dúvidas, consulte o administrador do sistema.\n"
        "\n"
        "<i>Versão 1.3 - Orquestrador Jurídico OLV</i>"
    )
